name: Test JS build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        haxe: [4.2.5]
      fail-fast: true
    runs-on: windows-latest

    steps:
      # Checkout & install haxe
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version

      # Install libs
      - run: haxe setup.hxml
      - run: haxelib list

      # Try to build
      - run: haxe build.js.hxml

